#!/bin/bash

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog

cd "${baseDir}"

# By convention, the patch name is the name of the directory containing the
# patch.
patchName="$(cd "${baseDir}"; basename "$(pwd -P)")"

outFile="${HOME}/Desktop/${patchName}.zip"

cd "${baseDir}/.."
rm -f "${outFile}" || exit 1
zip -r "${outFile}" "${patchName}" || exit 1
